version: "3"
services:
  userbot:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: bash -c "python main.py"
    tty: true
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
